#!/bin/bash

if [ $# -lt 1 ]; then
	echo "Syntax Error: Missing argument"
	echo 'Syntax: ./awk_balancing file_path'
else
	for i in $@; do
		if [ -f $i ]; then
			awk -F: '
				$1 == "B" {BAL=$NF; next ;}
				$1 == "M" {MIN=$NF; next;}
				$1 == "D" {BAL+=$NF;}
				($1 == "C") || ($1 == "W") {BAL-=$NF;}
				($1 == "C") || ($1 == "W") || ($1 == "D") {printf "%10-s %8.2f",$2,BAL;
				if ( BAL < MIN ) { printf" * Balance below minimum" }
				printf"\n"}
				END {printf "-\n%10-s %8.2f\n","Total",BAL;}
				
			' $i
		else
			echo "$1 is not a file or doesn't exist"
			echo "Syntax: ./awk_balancing file_path"
		fi
	done
fi
