#!/bin/bash

. /home/hesha/Documents/practice/lib.bash

isspaceavailable(){

	if [ $# -lt 2 ]; then
		echo "ERROR: Missing arguments."
		echo "Syntax: isspaceavailable DirectoryToCheck_Path AmountOfSpaceToCheck"
		return 1
	fi
	
	if [ ! -d $1 ]; then
		echo "ERROR: $1 is not a directory or it doesn't exist"
		echo "Syntax: isspaceavailable DirectoryToCheck_Path AmountOfSpaceToCheck"
		return 1
	fi
	
	case "$2" in
		''|*[!0-9]*) echo "ERROR: $2 is not an integer"; return 1;;
		*) ;;
	esac
	
	
	FreeSpace=`getSpaceFree $1`
	if [ ! $? -eq 0 ]; then
		echo "ERROR: Line 21 failed to execute."
		return 1;
	fi
	
	case "$3" in
		[Mm]|[Mm][Bb]) FreeSpace=`echo "$FreeSpace / 1024" | bc`;;
		[Gg]|[Gg][Bb]) FreeSpace=`echo "$FreeSpace / 1024 / 1024" | bc`;;
	esac
	
	
	if [ $FreeSpace -gt $2 ]; then
		echo "You have enough free space."
	else
		echo "Available space is less than $2${3:-"kb"}."
	fi

}


isspaceavailable $1 $2 $3
